### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by JB1985** [learnweb/moodle-mod_collabora#18]
Hello, 

i am not sure if it is a bug, but I have no idea anymore ...

I get in the Logs:

`[Sat Jul 18 21:01:09.368623 2020] [proxy_fcgi:error] [pid 13704:tid 140056627209984] [client 89.245.XXX.XX:5796] AH01071: Got error 'PHP message: PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /var/customers/webs/webXX/moodle/mod/collabora/classes/collabora.php on line 302PHP message: PHP Warning:  SimpleXMLElement::__construct(): Failed to connect to libreoffice.my.site port 9980: Connection refused in /var/customers/webs/webXX/moodle/mod/collabora/classes/collabora.php on line 302PHP message: PHP Warning:  SimpleXMLElement::__construct(): ^ in /var/customers/webs/webXX/moodle/mod/collabora/classes/collabora.php on line 302PHP message: Default exception handler: Fehler: String could not be parsed as XML Debug: \nError code: generalexceptionmessage\n* line 302 of /mod/collabora/classes/collabora.php: Exception thrown\n* line 302 of /mod/collabora/classes/collabora.php: call to SimpleXMLElement->__construct()\n* line 322 of /mod/collabora/classes/collabora.php: call to mod_collabora\\collabora->get_url_from_mimetype()\n* line 338 of /mod/collabora/classes/collabora.php: call to mod_collabora\\collabora->get_collabora_url()\n* line 113 of /mod/collabora/view.php: call to mod_collabora\\collabora->get_view_url()\n', referer: https://moodle.my.site/course/view.php?id=2`

Collabora Online is reachable, i dont know why I get the connection refused.

If I try to add the Collabora URL like the IP: https://123.123.123.123:8890/ I get the SSL do not match error, that is right.

Can be a problem with newtld Domains, like .berlin, .shop?

**Comment by Dagefoerde** [comment]
Hi, in the logs it says Failed to connect to `libreoffice.my.site port 9980: Connection refused`, so I'd suspect that a wrong host name has been set in some configuration. No, the new TLDs should not be an issue.

**Comment by JB1985** [comment]
But same setup with a .de Domain and it works.

The only differences are the domains and the certificate (Paid Wildcard Certificate to letsencrypt).

And if I try in the console to open the port 9980 it works.

**Comment by grabs** [comment]
I'm closing this now because there doesn't seem to be a problem with the plugin itself.
