### ISSUE TITLE
Plugin is not compatible with CollaboraOnline version 21.11

### ISSUE THREAD

**Issue by scroom** [learnweb/moodle-mod_collabora#30]
As described above. Collabora now recommends upgrading to version 21.11.

I get a 404 Not Found if I try to open a Collabora document.

Maybe because of changed reverse proxy settings?:
https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html

**Comment by grabs** [comment]
Hi,
the Moodle plugin works fine with Collabora 21.11.x
Everytime you change the Collabora version you have to clear the caches in Moodle.
If you use Collabora behind a reverse proxy you have to adjust the proxy rules to the new paths used since 21.11.
Best regards
Andreas
