### ISSUE TITLE
Last modification time offset when PHP time zone not UTC

### ISSUE THREAD

**Issue by jojoob** [learnweb/moodle-mod_collabora#31]
We noticed a time offset for the "Last modification time". It relates to the time zone set on the Moodle server. In our case UTC+2 (CEST) = -7200 seconds. Before the time change (UTC+1 (CET)) we experienced an offset of -3600 seconds.

![mod_collabora_negative_time](https://user-images.githubusercontent.com/4180675/161503222-2d2ac6a4-e5a7-4cb0-8bc0-3c84eea5c982.png)

**Comment by grabs** [comment]
Hi, thank you for this fix. It is integrated now.
