### ISSUE TITLE
prohibit download

### ISSUE THREAD

**Issue by pax77-dd** [learnweb/moodle-mod_collabora#34]
Hello,
how can I make the button/function "download" invisible for certain course roles or disallow the function "download" for certain course roles?
I did not find anything about this in the rights management of the course roles.
Best regards
Remo

**Comment by grabs** [comment]
Hi Remo,
I am sorry. Actually there is no way to do this. I try to introduce a new capability for that with the next release.
Best regards
Andreas

**Comment by grabs** [comment]
Hi Remo,
I am introduced a new capability for the direct download.
The new version is online.
Best regards
Andreas

**Comment by pax77-dd** [comment]
Hello Andreas,
Thank you for your information and the implementation of my suggestion.
But it seems that I can't use this version, because we are using moodle 3.10. Or can I just install the current version (v4.0-r5) manually over the v3.10-r3 version?
Thanks a lot for your support!
best regards
Remo
