### ISSUE TITLE
unable to save activity collaborative document

### ISSUE THREAD

**Issue by rimkov** [learnweb/moodle-mod_collabora#35]
hello
I installed a collabora code server in a Docker container and we integrated it into Moodle (a production and a test environment) using the mod_collabora plugin. Everything was working without problems until the day when some users (for now only 2) can no longer save and create the Moodle activity. The "Adding a collaborative document" page loops as if there were missing fields to fill in.

I deleted one of these Moodle accounts (test environment) and I recreated it and the problem disappeared. I'm tearing out the little hair I have left. do you have any advice?

moodle 3.11
plugin 3.11.r4

Thanks for your help.
Karim

**Comment by grabs** [comment]
Hi,
sorry for the late response.
Unfortunately, I have no idea what could be causing this behavior. This sound really strange to me. Maybe there are other additional plugins involved.
If you could find any about it, I'd be glad to hear from you.
Thank you!
