### ISSUE TITLE
Option "open in new window" doesn't work

### ISSUE THREAD

**Issue by abkoch** [learnweb/moodle-mod_collabora#36]
Hello,

the option "open in new window" doesn't work.

Moodle 4.0.4 (Build: 20220912)
mod_collabora 4.0-beta-3 (2022-04-04) - 2022030602

Changing the browser makes no difference.

Best regards
Andreas

**Comment by grabs** [comment]
Hi Andreas,
thank you for reporting this!
Now it is fixed and put into moodle plugin database.
Best regards
Andreas

**Comment by abkoch** [comment]
Dear Andreas,

thank you very much!

Best regards
your namesake
