### ISSUE TITLE
Notwendiger Parameter "sesskey" fehlt

### ISSUE THREAD

**Issue by abkoch** [learnweb/moodle-mod_collabora#37]
Hello,

after upgrading to v4.0-r3 (2022-11-06, 2022041902) it shows the following error (in German) when opening a "mod_collabora" activity (view.php):

Notwendiger Parameter "sesskey" fehlt (error/moodle/missingparam)

```
Debug-Info: 
Error code: missingparam

Stack trace: 
line 497 of /lib/setuplib.php: moodle_exception thrown
line 595 of /lib/moodlelib.php: call to print_error()
line 73 of /lib/sessionlib.php: call to required_param()
line 84 of /lib/sessionlib.php: call to confirm_sesskey()
line 267 of /mod/collabora/classes/collabora.php: call to require_sesskey()
line 77 of /mod/collabora/view.php: call to mod_collabora\collabora->process_lock_unlock()
```

Best regards
Andreas

**Comment by grabs** [comment]
Hi Andreas,
I am so sorry :(. I moved the call require_sesskey() a few lines to far upwards.
It now is fixed and online.
Thanks for the quick info!
Best regards
Andreas

**Comment by abkoch** [comment]
Great! Thanks for your immediate patch.
