### ISSUE TITLE
Bundle.js Error in Moodle frame.

### ISSUE THREAD

**Issue by bencellis** [learnweb/moodle-mod_collabora#5]
I always get the 
_Uncaught TypeError: Cannot set property 'permission' of undefined
    at NewClass.connect (bundle.js:41)
    at NewClass.loadDocument (bundle.js:42)
    at bundle.js:63
    at bundle.js:63_
in the console in both in Firefox and Chrome - Moodle 3.5.4 and Collabora 4.0.6.  Any ideas?  The documents fail to load for editing or viewing - only the menu shows.

**Comment by Dagefoerde** [comment]
Hi, thanks for your report and for your interest in using the plugin. As there is no "bundle.js" in this plugin, I doubt that this is a mod_collabora problem (or at least one that we could fix). Also, as far as I know there is no bundle.js in Moodle.

As a consequence, I believe that this is a problem with Collabora itself. Please report your issue with them. Thank you!
